COPTS=-Wall -g -std=c++20

TARGETS := \
	task-03-1 task-03-2 task-03-3 task-03-4 \
	task-04-1 task-04-2 task-04-3 task-04-4 \
	task-05-1 task-05-2 task-05-3

all: $(TARGETS)

clean:
	-rm $(TARGETS)

task-03-1: task-03-1.cpp
	g++ $(COPTS) $^ -o $@

task-03-2: task-03-2.cpp
	g++ $(COPTS) $^ -o $@

task-03-3: task-03-3.cpp
	g++ $(COPTS) $^ -o $@

task-03-4: task-03-4.cpp
	g++ $(COPTS) $^ -o $@

task-04-1: task-04-1.cpp
	g++ $(COPTS) $^ -o $@

task-04-2: task-04-2.cpp
	g++ $(COPTS) $^ -o $@

task-04-3: task-04-3.cpp
	g++ $(COPTS) $^ -o $@

task-04-4: task-04-4.cpp
	g++ $(COPTS) $^ -o $@

task-05-1: task-05-1.cpp
	g++ $(COPTS) $^ -o $@

task-05-2: task-05-2.cpp
	g++ $(COPTS) $^ -o $@

task-05-3: task-05-3.cpp
	g++ $(COPTS) $^ -o $@
